### ISSUE TITLE
[Melhoria] Implementar responsividade fase 1

### ISSUE THREAD

**Issue by mario-adriano** [mario-adriano/aliato-project-manager#6]
# Responsividade

A responsividade de uma aplicação WEB é a capacidade dessa aplicação se adaptar a tamanhos diferentes de tela e permitir aos usuários o uso completo do produto independentemente do dispositivo utilizado.

## Estratégia

Para implementar a responsividade da nossa aplicação usarei como referência essa tarefa para centralizar quais telas estão sendo tratadas.

**Comment by oArthurCandido** [comment]
# Responsividade
### Fiz a primeira sessão de melhorias na responsividade da aplicação, seguem demonstrações em imagens:
# Menu lateral
## Antes
Menu sempre aberto
![image](https://github.com/user-attachments/assets/a4f04df2-ede2-4f85-8abb-434cba6a0fc8)

## Agora
Menu dinâmico
![image](https://github.com/user-attachments/assets/5cea66db-136c-4aed-98e7-d864704601f9) ![image](https://github.com/user-attachments/assets/d398ede5-37da-437b-a53b-d053f2cea319)

# Botões de ação

## Antes
Botões empilhados sem divisão
![image](https://github.com/user-attachments/assets/28d3ac84-aa7b-4442-b0ae-fa33b8b13559)

## Agora
Botões sem quebra de linha e separados
![image](https://github.com/user-attachments/assets/99002394-3ba5-459a-911c-ef4a0e97fc2b)


# Formulários de cadastro e edição de operadores, fases, clientes e projetos

## Antes
Elementos escapavam da tela 
![image](https://github.com/user-attachments/assets/cf914d81-c377-4d8c-8cd3-9032e0c4735d)


## Agora
Elementos contidos na tela e 100% visíveis
![image](https://github.com/user-attachments/assets/7370cf0f-7905-4f54-877f-74ef79b7c0ba)
